### ISSUE TITLE
Upgrade CY to latest stable version

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-e2e-cypress#77]
## TODO
- [x] upgrade to v10
- [x] upgrade to v11
- [x] upgrade to v12
- [x] upgrade to v13
- [x] run tests in docker and see if they pass
- [x] fix basic tests
- [x] fix advanced tests

## Task that need to be done so tests can pass
- https://github.com/cortezaproject/corteza/issues/1524
