### ISSUE TITLE
Cypress - Admin - Auth Settings - Enable Avatar (Second layer of testing)

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-e2e-cypress#88]
### Description

Test the functionality for showing and hiding the functionality to configure user avatar

### Todo

- [ ] Check if it's enabled by default
- [ ] Check if the user is able to see the dedicated avatar section in their profile
- [ ] Uncheck the checkbox and verify the change has been applied
